export const tees = [
  {
    id: 0,
    brand: "Piece of 8",
    description: "Short description",
    label: "tee",
    name: "The lovers Black",
    path: "/tees",
    price: 17.95,
    src: "/images/tees/t1.PNG",
  },
  {
    id: 1,
    brand: "Piece of 8",
    description: "Short description",
    label: "tee",
    name: "The lovers White",
    path: "/tees",
    price: 17.95,
    src: "/images/tees/t2.PNG",
  },
  {
    id: 2,
    brand: "Piece of 8",
    description: "Short description",
    label: "tee",
    name: "Burning Churches White",
    path: "/tees",
    price: 17.95,
    src: "/images/tees/t3.PNG",
  },
  {
    id: 4,
    brand: "Piece of 8",
    description: "Short description",
    label: "tee",
    name: "Japan Memories White",
    path: "/tees",
    price: 17.95,
    src: "/images/tees/t4.jpeg",
  },
  {
    id: 10,
    brand: "Piece of 8",
    description: "Short description",
    label: "tee",
    name: "Corpus Christi Black",
    path: "/tees",
    price: 17.95,
    src: "/images/tees/t5.PNG",
  },
];
